-- Crear bases de datos
CREATE DATABASE TESORO;
CREATE TABLE TESORO.DEBE(ID INT NOT NULL AUTO_INCREMENT, M2 FLOAT, CONCEPTO VARCHAR(99),PRIMARY KEY(ID));
CREATE TABLE TESORO.HABER(ID INT NOT NULL AUTO_INCREMENT, M2 FLOAT, CONCEPTO VARCHAR(99),PRIMARY KEY(ID));
CREATE DATABASE FAMILIA;
CREATE TABLE FAMILIA.DEBE(ID INT NOT NULL AUTO_INCREMENT, M2 FLOAT, CONCEPTO VARCHAR(99),PRIMARY KEY(ID));
CREATE TABLE FAMILIA.HABER(ID INT NOT NULL AUTO_INCREMENT, M2 FLOAT, CONCEPTO VARCHAR(99),PRIMARY KEY(ID));
CREATE DATABASE BANCO_CENTRAL;
CREATE TABLE BANCO_CENTRAL.DEBE(ID INT NOT NULL AUTO_INCREMENT, M2 FLOAT, CONCEPTO VARCHAR(99),PRIMARY KEY(ID));
CREATE TABLE BANCO_CENTRAL.HABER(ID INT NOT NULL AUTO_INCREMENT, M2 FLOAT, CONCEPTO VARCHAR(99),PRIMARY KEY(ID));
CREATE DATABASE BANCO;
CREATE TABLE BANCO.DEBE(ID INT NOT NULL AUTO_INCREMENT, M2 FLOAT, CONCEPTO VARCHAR(99),PRIMARY KEY(ID));
CREATE TABLE BANCO.HABER(ID INT NOT NULL AUTO_INCREMENT, M2 FLOAT, CONCEPTO VARCHAR(99),PRIMARY KEY(ID));
COMMIT;

-- Dinero desde el sector público
INSERT INTO TESORO.DEBE (M2,CONCEPTO) VALUES(0,"Balance");
INSERT INTO TESORO.HABER (M2,CONCEPTO) VALUES(0,"Balance");
SELECT * FROM TESORO.DEBE;
SELECT * FROM TESORO.HABER;

SET SQL_SAFE_UPDATES = 0;
UPDATE TESORO.DEBE SET M2 = M2 - 1280;
UPDATE TESORO.DEBE SET CONCEPTO = "Banco Central";
UPDATE TESORO.HABER SET M2 = M2 - 1280;
UPDATE TESORO.HABER SET CONCEPTO = "Patrimonio Neto";
COMMIT;
-- BC
INSERT INTO BANCO_CENTRAL.HABER(M2,CONCEPTO) VALUES(0,"Tesoro");
INSERT INTO BANCO_CENTRAL.HABER(M2,CONCEPTO) VALUES(0,"Banco");
SELECT * FROM TESORO.DEBE;
SELECT * FROM BANCO_CENTRAL.HABER;
UPDATE BANCO_CENTRAL.HABER SET M2 = M2 - 1280 WHERE CONCEPTO = "Tesoro";
UPDATE BANCO_CENTRAL.HABER SET M2 = M2 + 1280 WHERE CONCEPTO = "Banco";
COMMIT;
-- Banco
INSERT INTO BANCO.DEBE(M2,CONCEPTO) VALUES(0,"Reservas");
INSERT INTO BANCO.HABER(M2,CONCEPTO) VALUES(0,"Nómina");
SELECT * FROM BANCO.DEBE;
SELECT * FROM BANCO.HABER;

UPDATE BANCO.DEBE SET M2 = M2 + 1280 WHERE CONCEPTO = "Reservas";
UPDATE BANCO.HABER SET M2 = M2 - 1280 WHERE CONCEPTO = "Nómina";
COMMIT;
-- Sector privado
INSERT INTO FAMILIA.DEBE(M2,CONCEPTO) VALUES(0,"Nómina");
SELECT * FROM FAMILIA.DEBE;

UPDATE FAMILIA.DEBE SET M2 = M2 + 1280;
